baseURL      = "https://deadlockblog.github.io/"
title        = "Un paranoico profesional"
languageCode = "es-es"
theme        = "risotto"

[author]
  name = "deadlock"

[params]
  noindex = false

[params.theme]
  palette = "base16-dark"

[params.about]
  title    = "Un paranoico profesional"
  description = "Notas desde el lado paranoico del teclado. Pentesting, auditoria, inteligencia y otras paranoias utiles."
  logo     = ""

[[params.socialLinks]]
  title = "GitHub"
  url   = "https://github.com/Deadlock-101"

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts/"
    weight     = 10

  [[menu.main]]
    identifier = "tags"
    name       = "tags"
    url        = "/tags/"
    weight     = 20

  [[menu.main]]
    identifier = "about"
    name       = "whoami"
    url        = "/about/"
    weight     = 30

[taxonomies]
  category = "categorias"
  tag      = "tags"

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true